# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vfrocrain/OOP_indie_studio_2019

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vfrocrain/OOP_indie_studio_2019

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vfrocrain/OOP_indie_studio_2019/CMakeFiles /home/vfrocrain/OOP_indie_studio_2019/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vfrocrain/OOP_indie_studio_2019/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

src/core/main.o: src/core/main.cpp.o

.PHONY : src/core/main.o

# target to build an object file
src/core/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/core/main.cpp.o
.PHONY : src/core/main.cpp.o

src/core/main.i: src/core/main.cpp.i

.PHONY : src/core/main.i

# target to preprocess a source file
src/core/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/core/main.cpp.i
.PHONY : src/core/main.cpp.i

src/core/main.s: src/core/main.cpp.s

.PHONY : src/core/main.s

# target to generate assembly for a file
src/core/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/core/main.cpp.s
.PHONY : src/core/main.cpp.s

src/entity/AEntity.o: src/entity/AEntity.cpp.o

.PHONY : src/entity/AEntity.o

# target to build an object file
src/entity/AEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/AEntity.cpp.o
.PHONY : src/entity/AEntity.cpp.o

src/entity/AEntity.i: src/entity/AEntity.cpp.i

.PHONY : src/entity/AEntity.i

# target to preprocess a source file
src/entity/AEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/AEntity.cpp.i
.PHONY : src/entity/AEntity.cpp.i

src/entity/AEntity.s: src/entity/AEntity.cpp.s

.PHONY : src/entity/AEntity.s

# target to generate assembly for a file
src/entity/AEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/AEntity.cpp.s
.PHONY : src/entity/AEntity.cpp.s

src/entity/bomb/Bomb.o: src/entity/bomb/Bomb.cpp.o

.PHONY : src/entity/bomb/Bomb.o

# target to build an object file
src/entity/bomb/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/bomb/Bomb.cpp.o
.PHONY : src/entity/bomb/Bomb.cpp.o

src/entity/bomb/Bomb.i: src/entity/bomb/Bomb.cpp.i

.PHONY : src/entity/bomb/Bomb.i

# target to preprocess a source file
src/entity/bomb/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/bomb/Bomb.cpp.i
.PHONY : src/entity/bomb/Bomb.cpp.i

src/entity/bomb/Bomb.s: src/entity/bomb/Bomb.cpp.s

.PHONY : src/entity/bomb/Bomb.s

# target to generate assembly for a file
src/entity/bomb/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/bomb/Bomb.cpp.s
.PHONY : src/entity/bomb/Bomb.cpp.s

src/entity/character/ACharacter.o: src/entity/character/ACharacter.cpp.o

.PHONY : src/entity/character/ACharacter.o

# target to build an object file
src/entity/character/ACharacter.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/ACharacter.cpp.o
.PHONY : src/entity/character/ACharacter.cpp.o

src/entity/character/ACharacter.i: src/entity/character/ACharacter.cpp.i

.PHONY : src/entity/character/ACharacter.i

# target to preprocess a source file
src/entity/character/ACharacter.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/ACharacter.cpp.i
.PHONY : src/entity/character/ACharacter.cpp.i

src/entity/character/ACharacter.s: src/entity/character/ACharacter.cpp.s

.PHONY : src/entity/character/ACharacter.s

# target to generate assembly for a file
src/entity/character/ACharacter.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/ACharacter.cpp.s
.PHONY : src/entity/character/ACharacter.cpp.s

src/entity/character/AI/AI.o: src/entity/character/AI/AI.cpp.o

.PHONY : src/entity/character/AI/AI.o

# target to build an object file
src/entity/character/AI/AI.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/AI/AI.cpp.o
.PHONY : src/entity/character/AI/AI.cpp.o

src/entity/character/AI/AI.i: src/entity/character/AI/AI.cpp.i

.PHONY : src/entity/character/AI/AI.i

# target to preprocess a source file
src/entity/character/AI/AI.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/AI/AI.cpp.i
.PHONY : src/entity/character/AI/AI.cpp.i

src/entity/character/AI/AI.s: src/entity/character/AI/AI.cpp.s

.PHONY : src/entity/character/AI/AI.s

# target to generate assembly for a file
src/entity/character/AI/AI.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/AI/AI.cpp.s
.PHONY : src/entity/character/AI/AI.cpp.s

src/entity/character/player/APlayerController.o: src/entity/character/player/APlayerController.cpp.o

.PHONY : src/entity/character/player/APlayerController.o

# target to build an object file
src/entity/character/player/APlayerController.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/player/APlayerController.cpp.o
.PHONY : src/entity/character/player/APlayerController.cpp.o

src/entity/character/player/APlayerController.i: src/entity/character/player/APlayerController.cpp.i

.PHONY : src/entity/character/player/APlayerController.i

# target to preprocess a source file
src/entity/character/player/APlayerController.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/player/APlayerController.cpp.i
.PHONY : src/entity/character/player/APlayerController.cpp.i

src/entity/character/player/APlayerController.s: src/entity/character/player/APlayerController.cpp.s

.PHONY : src/entity/character/player/APlayerController.s

# target to generate assembly for a file
src/entity/character/player/APlayerController.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/player/APlayerController.cpp.s
.PHONY : src/entity/character/player/APlayerController.cpp.s

src/entity/character/player/Control.o: src/entity/character/player/Control.cpp.o

.PHONY : src/entity/character/player/Control.o

# target to build an object file
src/entity/character/player/Control.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/player/Control.cpp.o
.PHONY : src/entity/character/player/Control.cpp.o

src/entity/character/player/Control.i: src/entity/character/player/Control.cpp.i

.PHONY : src/entity/character/player/Control.i

# target to preprocess a source file
src/entity/character/player/Control.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/player/Control.cpp.i
.PHONY : src/entity/character/player/Control.cpp.i

src/entity/character/player/Control.s: src/entity/character/player/Control.cpp.s

.PHONY : src/entity/character/player/Control.s

# target to generate assembly for a file
src/entity/character/player/Control.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/player/Control.cpp.s
.PHONY : src/entity/character/player/Control.cpp.s

src/entity/character/player/Player.o: src/entity/character/player/Player.cpp.o

.PHONY : src/entity/character/player/Player.o

# target to build an object file
src/entity/character/player/Player.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/player/Player.cpp.o
.PHONY : src/entity/character/player/Player.cpp.o

src/entity/character/player/Player.i: src/entity/character/player/Player.cpp.i

.PHONY : src/entity/character/player/Player.i

# target to preprocess a source file
src/entity/character/player/Player.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/player/Player.cpp.i
.PHONY : src/entity/character/player/Player.cpp.i

src/entity/character/player/Player.s: src/entity/character/player/Player.cpp.s

.PHONY : src/entity/character/player/Player.s

# target to generate assembly for a file
src/entity/character/player/Player.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/character/player/Player.cpp.s
.PHONY : src/entity/character/player/Player.cpp.s

src/entity/fire/Fire.o: src/entity/fire/Fire.cpp.o

.PHONY : src/entity/fire/Fire.o

# target to build an object file
src/entity/fire/Fire.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/fire/Fire.cpp.o
.PHONY : src/entity/fire/Fire.cpp.o

src/entity/fire/Fire.i: src/entity/fire/Fire.cpp.i

.PHONY : src/entity/fire/Fire.i

# target to preprocess a source file
src/entity/fire/Fire.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/fire/Fire.cpp.i
.PHONY : src/entity/fire/Fire.cpp.i

src/entity/fire/Fire.s: src/entity/fire/Fire.cpp.s

.PHONY : src/entity/fire/Fire.s

# target to generate assembly for a file
src/entity/fire/Fire.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/fire/Fire.cpp.s
.PHONY : src/entity/fire/Fire.cpp.s

src/entity/power_up/APowerUp.o: src/entity/power_up/APowerUp.cpp.o

.PHONY : src/entity/power_up/APowerUp.o

# target to build an object file
src/entity/power_up/APowerUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/power_up/APowerUp.cpp.o
.PHONY : src/entity/power_up/APowerUp.cpp.o

src/entity/power_up/APowerUp.i: src/entity/power_up/APowerUp.cpp.i

.PHONY : src/entity/power_up/APowerUp.i

# target to preprocess a source file
src/entity/power_up/APowerUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/power_up/APowerUp.cpp.i
.PHONY : src/entity/power_up/APowerUp.cpp.i

src/entity/power_up/APowerUp.s: src/entity/power_up/APowerUp.cpp.s

.PHONY : src/entity/power_up/APowerUp.s

# target to generate assembly for a file
src/entity/power_up/APowerUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/power_up/APowerUp.cpp.s
.PHONY : src/entity/power_up/APowerUp.cpp.s

src/entity/power_up/PowerUp.o: src/entity/power_up/PowerUp.cpp.o

.PHONY : src/entity/power_up/PowerUp.o

# target to build an object file
src/entity/power_up/PowerUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/power_up/PowerUp.cpp.o
.PHONY : src/entity/power_up/PowerUp.cpp.o

src/entity/power_up/PowerUp.i: src/entity/power_up/PowerUp.cpp.i

.PHONY : src/entity/power_up/PowerUp.i

# target to preprocess a source file
src/entity/power_up/PowerUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/power_up/PowerUp.cpp.i
.PHONY : src/entity/power_up/PowerUp.cpp.i

src/entity/power_up/PowerUp.s: src/entity/power_up/PowerUp.cpp.s

.PHONY : src/entity/power_up/PowerUp.s

# target to generate assembly for a file
src/entity/power_up/PowerUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/power_up/PowerUp.cpp.s
.PHONY : src/entity/power_up/PowerUp.cpp.s

src/entity/wall/AWall.o: src/entity/wall/AWall.cpp.o

.PHONY : src/entity/wall/AWall.o

# target to build an object file
src/entity/wall/AWall.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/wall/AWall.cpp.o
.PHONY : src/entity/wall/AWall.cpp.o

src/entity/wall/AWall.i: src/entity/wall/AWall.cpp.i

.PHONY : src/entity/wall/AWall.i

# target to preprocess a source file
src/entity/wall/AWall.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/wall/AWall.cpp.i
.PHONY : src/entity/wall/AWall.cpp.i

src/entity/wall/AWall.s: src/entity/wall/AWall.cpp.s

.PHONY : src/entity/wall/AWall.s

# target to generate assembly for a file
src/entity/wall/AWall.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/wall/AWall.cpp.s
.PHONY : src/entity/wall/AWall.cpp.s

src/entity/wall/Wall.o: src/entity/wall/Wall.cpp.o

.PHONY : src/entity/wall/Wall.o

# target to build an object file
src/entity/wall/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/wall/Wall.cpp.o
.PHONY : src/entity/wall/Wall.cpp.o

src/entity/wall/Wall.i: src/entity/wall/Wall.cpp.i

.PHONY : src/entity/wall/Wall.i

# target to preprocess a source file
src/entity/wall/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/wall/Wall.cpp.i
.PHONY : src/entity/wall/Wall.cpp.i

src/entity/wall/Wall.s: src/entity/wall/Wall.cpp.s

.PHONY : src/entity/wall/Wall.s

# target to generate assembly for a file
src/entity/wall/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/entity/wall/Wall.cpp.s
.PHONY : src/entity/wall/Wall.cpp.s

src/finder/AFinder.o: src/finder/AFinder.cpp.o

.PHONY : src/finder/AFinder.o

# target to build an object file
src/finder/AFinder.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/finder/AFinder.cpp.o
.PHONY : src/finder/AFinder.cpp.o

src/finder/AFinder.i: src/finder/AFinder.cpp.i

.PHONY : src/finder/AFinder.i

# target to preprocess a source file
src/finder/AFinder.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/finder/AFinder.cpp.i
.PHONY : src/finder/AFinder.cpp.i

src/finder/AFinder.s: src/finder/AFinder.cpp.s

.PHONY : src/finder/AFinder.s

# target to generate assembly for a file
src/finder/AFinder.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/finder/AFinder.cpp.s
.PHONY : src/finder/AFinder.cpp.s

src/finder/Finder.o: src/finder/Finder.cpp.o

.PHONY : src/finder/Finder.o

# target to build an object file
src/finder/Finder.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/finder/Finder.cpp.o
.PHONY : src/finder/Finder.cpp.o

src/finder/Finder.i: src/finder/Finder.cpp.i

.PHONY : src/finder/Finder.i

# target to preprocess a source file
src/finder/Finder.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/finder/Finder.cpp.i
.PHONY : src/finder/Finder.cpp.i

src/finder/Finder.s: src/finder/Finder.cpp.s

.PHONY : src/finder/Finder.s

# target to generate assembly for a file
src/finder/Finder.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/finder/Finder.cpp.s
.PHONY : src/finder/Finder.cpp.s

src/map/Entities.o: src/map/Entities.cpp.o

.PHONY : src/map/Entities.o

# target to build an object file
src/map/Entities.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/Entities.cpp.o
.PHONY : src/map/Entities.cpp.o

src/map/Entities.i: src/map/Entities.cpp.i

.PHONY : src/map/Entities.i

# target to preprocess a source file
src/map/Entities.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/Entities.cpp.i
.PHONY : src/map/Entities.cpp.i

src/map/Entities.s: src/map/Entities.cpp.s

.PHONY : src/map/Entities.s

# target to generate assembly for a file
src/map/Entities.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/Entities.cpp.s
.PHONY : src/map/Entities.cpp.s

src/map/Logger.o: src/map/Logger.cpp.o

.PHONY : src/map/Logger.o

# target to build an object file
src/map/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/Logger.cpp.o
.PHONY : src/map/Logger.cpp.o

src/map/Logger.i: src/map/Logger.cpp.i

.PHONY : src/map/Logger.i

# target to preprocess a source file
src/map/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/Logger.cpp.i
.PHONY : src/map/Logger.cpp.i

src/map/Logger.s: src/map/Logger.cpp.s

.PHONY : src/map/Logger.s

# target to generate assembly for a file
src/map/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/Logger.cpp.s
.PHONY : src/map/Logger.cpp.s

src/map/MapGenerator.o: src/map/MapGenerator.cpp.o

.PHONY : src/map/MapGenerator.o

# target to build an object file
src/map/MapGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/MapGenerator.cpp.o
.PHONY : src/map/MapGenerator.cpp.o

src/map/MapGenerator.i: src/map/MapGenerator.cpp.i

.PHONY : src/map/MapGenerator.i

# target to preprocess a source file
src/map/MapGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/MapGenerator.cpp.i
.PHONY : src/map/MapGenerator.cpp.i

src/map/MapGenerator.s: src/map/MapGenerator.cpp.s

.PHONY : src/map/MapGenerator.s

# target to generate assembly for a file
src/map/MapGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/map/MapGenerator.cpp.s
.PHONY : src/map/MapGenerator.cpp.s

src/scenes/AScene.o: src/scenes/AScene.cpp.o

.PHONY : src/scenes/AScene.o

# target to build an object file
src/scenes/AScene.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/AScene.cpp.o
.PHONY : src/scenes/AScene.cpp.o

src/scenes/AScene.i: src/scenes/AScene.cpp.i

.PHONY : src/scenes/AScene.i

# target to preprocess a source file
src/scenes/AScene.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/AScene.cpp.i
.PHONY : src/scenes/AScene.cpp.i

src/scenes/AScene.s: src/scenes/AScene.cpp.s

.PHONY : src/scenes/AScene.s

# target to generate assembly for a file
src/scenes/AScene.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/AScene.cpp.s
.PHONY : src/scenes/AScene.cpp.s

src/scenes/AScenePlayerControls.o: src/scenes/AScenePlayerControls.cpp.o

.PHONY : src/scenes/AScenePlayerControls.o

# target to build an object file
src/scenes/AScenePlayerControls.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/AScenePlayerControls.cpp.o
.PHONY : src/scenes/AScenePlayerControls.cpp.o

src/scenes/AScenePlayerControls.i: src/scenes/AScenePlayerControls.cpp.i

.PHONY : src/scenes/AScenePlayerControls.i

# target to preprocess a source file
src/scenes/AScenePlayerControls.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/AScenePlayerControls.cpp.i
.PHONY : src/scenes/AScenePlayerControls.cpp.i

src/scenes/AScenePlayerControls.s: src/scenes/AScenePlayerControls.cpp.s

.PHONY : src/scenes/AScenePlayerControls.s

# target to generate assembly for a file
src/scenes/AScenePlayerControls.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/AScenePlayerControls.cpp.s
.PHONY : src/scenes/AScenePlayerControls.cpp.s

src/scenes/ControlMenu.o: src/scenes/ControlMenu.cpp.o

.PHONY : src/scenes/ControlMenu.o

# target to build an object file
src/scenes/ControlMenu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/ControlMenu.cpp.o
.PHONY : src/scenes/ControlMenu.cpp.o

src/scenes/ControlMenu.i: src/scenes/ControlMenu.cpp.i

.PHONY : src/scenes/ControlMenu.i

# target to preprocess a source file
src/scenes/ControlMenu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/ControlMenu.cpp.i
.PHONY : src/scenes/ControlMenu.cpp.i

src/scenes/ControlMenu.s: src/scenes/ControlMenu.cpp.s

.PHONY : src/scenes/ControlMenu.s

# target to generate assembly for a file
src/scenes/ControlMenu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/ControlMenu.cpp.s
.PHONY : src/scenes/ControlMenu.cpp.s

src/scenes/EventListener.o: src/scenes/EventListener.cpp.o

.PHONY : src/scenes/EventListener.o

# target to build an object file
src/scenes/EventListener.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/EventListener.cpp.o
.PHONY : src/scenes/EventListener.cpp.o

src/scenes/EventListener.i: src/scenes/EventListener.cpp.i

.PHONY : src/scenes/EventListener.i

# target to preprocess a source file
src/scenes/EventListener.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/EventListener.cpp.i
.PHONY : src/scenes/EventListener.cpp.i

src/scenes/EventListener.s: src/scenes/EventListener.cpp.s

.PHONY : src/scenes/EventListener.s

# target to generate assembly for a file
src/scenes/EventListener.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/EventListener.cpp.s
.PHONY : src/scenes/EventListener.cpp.s

src/scenes/Game.o: src/scenes/Game.cpp.o

.PHONY : src/scenes/Game.o

# target to build an object file
src/scenes/Game.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Game.cpp.o
.PHONY : src/scenes/Game.cpp.o

src/scenes/Game.i: src/scenes/Game.cpp.i

.PHONY : src/scenes/Game.i

# target to preprocess a source file
src/scenes/Game.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Game.cpp.i
.PHONY : src/scenes/Game.cpp.i

src/scenes/Game.s: src/scenes/Game.cpp.s

.PHONY : src/scenes/Game.s

# target to generate assembly for a file
src/scenes/Game.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Game.cpp.s
.PHONY : src/scenes/Game.cpp.s

src/scenes/GameOver.o: src/scenes/GameOver.cpp.o

.PHONY : src/scenes/GameOver.o

# target to build an object file
src/scenes/GameOver.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/GameOver.cpp.o
.PHONY : src/scenes/GameOver.cpp.o

src/scenes/GameOver.i: src/scenes/GameOver.cpp.i

.PHONY : src/scenes/GameOver.i

# target to preprocess a source file
src/scenes/GameOver.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/GameOver.cpp.i
.PHONY : src/scenes/GameOver.cpp.i

src/scenes/GameOver.s: src/scenes/GameOver.cpp.s

.PHONY : src/scenes/GameOver.s

# target to generate assembly for a file
src/scenes/GameOver.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/GameOver.cpp.s
.PHONY : src/scenes/GameOver.cpp.s

src/scenes/MainMenu.o: src/scenes/MainMenu.cpp.o

.PHONY : src/scenes/MainMenu.o

# target to build an object file
src/scenes/MainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/MainMenu.cpp.o
.PHONY : src/scenes/MainMenu.cpp.o

src/scenes/MainMenu.i: src/scenes/MainMenu.cpp.i

.PHONY : src/scenes/MainMenu.i

# target to preprocess a source file
src/scenes/MainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/MainMenu.cpp.i
.PHONY : src/scenes/MainMenu.cpp.i

src/scenes/MainMenu.s: src/scenes/MainMenu.cpp.s

.PHONY : src/scenes/MainMenu.s

# target to generate assembly for a file
src/scenes/MainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/MainMenu.cpp.s
.PHONY : src/scenes/MainMenu.cpp.s

src/scenes/Menu.o: src/scenes/Menu.cpp.o

.PHONY : src/scenes/Menu.o

# target to build an object file
src/scenes/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Menu.cpp.o
.PHONY : src/scenes/Menu.cpp.o

src/scenes/Menu.i: src/scenes/Menu.cpp.i

.PHONY : src/scenes/Menu.i

# target to preprocess a source file
src/scenes/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Menu.cpp.i
.PHONY : src/scenes/Menu.cpp.i

src/scenes/Menu.s: src/scenes/Menu.cpp.s

.PHONY : src/scenes/Menu.s

# target to generate assembly for a file
src/scenes/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Menu.cpp.s
.PHONY : src/scenes/Menu.cpp.s

src/scenes/MenuPlayer.o: src/scenes/MenuPlayer.cpp.o

.PHONY : src/scenes/MenuPlayer.o

# target to build an object file
src/scenes/MenuPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/MenuPlayer.cpp.o
.PHONY : src/scenes/MenuPlayer.cpp.o

src/scenes/MenuPlayer.i: src/scenes/MenuPlayer.cpp.i

.PHONY : src/scenes/MenuPlayer.i

# target to preprocess a source file
src/scenes/MenuPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/MenuPlayer.cpp.i
.PHONY : src/scenes/MenuPlayer.cpp.i

src/scenes/MenuPlayer.s: src/scenes/MenuPlayer.cpp.s

.PHONY : src/scenes/MenuPlayer.s

# target to generate assembly for a file
src/scenes/MenuPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/MenuPlayer.cpp.s
.PHONY : src/scenes/MenuPlayer.cpp.s

src/scenes/Options.o: src/scenes/Options.cpp.o

.PHONY : src/scenes/Options.o

# target to build an object file
src/scenes/Options.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Options.cpp.o
.PHONY : src/scenes/Options.cpp.o

src/scenes/Options.i: src/scenes/Options.cpp.i

.PHONY : src/scenes/Options.i

# target to preprocess a source file
src/scenes/Options.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Options.cpp.i
.PHONY : src/scenes/Options.cpp.i

src/scenes/Options.s: src/scenes/Options.cpp.s

.PHONY : src/scenes/Options.s

# target to generate assembly for a file
src/scenes/Options.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Options.cpp.s
.PHONY : src/scenes/Options.cpp.s

src/scenes/Pause.o: src/scenes/Pause.cpp.o

.PHONY : src/scenes/Pause.o

# target to build an object file
src/scenes/Pause.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Pause.cpp.o
.PHONY : src/scenes/Pause.cpp.o

src/scenes/Pause.i: src/scenes/Pause.cpp.i

.PHONY : src/scenes/Pause.i

# target to preprocess a source file
src/scenes/Pause.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Pause.cpp.i
.PHONY : src/scenes/Pause.cpp.i

src/scenes/Pause.s: src/scenes/Pause.cpp.s

.PHONY : src/scenes/Pause.s

# target to generate assembly for a file
src/scenes/Pause.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Pause.cpp.s
.PHONY : src/scenes/Pause.cpp.s

src/scenes/Scenes.o: src/scenes/Scenes.cpp.o

.PHONY : src/scenes/Scenes.o

# target to build an object file
src/scenes/Scenes.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Scenes.cpp.o
.PHONY : src/scenes/Scenes.cpp.o

src/scenes/Scenes.i: src/scenes/Scenes.cpp.i

.PHONY : src/scenes/Scenes.i

# target to preprocess a source file
src/scenes/Scenes.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Scenes.cpp.i
.PHONY : src/scenes/Scenes.cpp.i

src/scenes/Scenes.s: src/scenes/Scenes.cpp.s

.PHONY : src/scenes/Scenes.s

# target to generate assembly for a file
src/scenes/Scenes.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/Scenes.cpp.s
.PHONY : src/scenes/Scenes.cpp.s

src/scenes/WinMenu.o: src/scenes/WinMenu.cpp.o

.PHONY : src/scenes/WinMenu.o

# target to build an object file
src/scenes/WinMenu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/WinMenu.cpp.o
.PHONY : src/scenes/WinMenu.cpp.o

src/scenes/WinMenu.i: src/scenes/WinMenu.cpp.i

.PHONY : src/scenes/WinMenu.i

# target to preprocess a source file
src/scenes/WinMenu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/WinMenu.cpp.i
.PHONY : src/scenes/WinMenu.cpp.i

src/scenes/WinMenu.s: src/scenes/WinMenu.cpp.s

.PHONY : src/scenes/WinMenu.s

# target to generate assembly for a file
src/scenes/WinMenu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/scenes/WinMenu.cpp.s
.PHONY : src/scenes/WinMenu.cpp.s

src/tools/Tools.o: src/tools/Tools.cpp.o

.PHONY : src/tools/Tools.o

# target to build an object file
src/tools/Tools.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/tools/Tools.cpp.o
.PHONY : src/tools/Tools.cpp.o

src/tools/Tools.i: src/tools/Tools.cpp.i

.PHONY : src/tools/Tools.i

# target to preprocess a source file
src/tools/Tools.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/tools/Tools.cpp.i
.PHONY : src/tools/Tools.cpp.i

src/tools/Tools.s: src/tools/Tools.cpp.s

.PHONY : src/tools/Tools.s

# target to generate assembly for a file
src/tools/Tools.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/tools/Tools.cpp.s
.PHONY : src/tools/Tools.cpp.s

src/utils/FileReader.o: src/utils/FileReader.cpp.o

.PHONY : src/utils/FileReader.o

# target to build an object file
src/utils/FileReader.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/utils/FileReader.cpp.o
.PHONY : src/utils/FileReader.cpp.o

src/utils/FileReader.i: src/utils/FileReader.cpp.i

.PHONY : src/utils/FileReader.i

# target to preprocess a source file
src/utils/FileReader.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/utils/FileReader.cpp.i
.PHONY : src/utils/FileReader.cpp.i

src/utils/FileReader.s: src/utils/FileReader.cpp.s

.PHONY : src/utils/FileReader.s

# target to generate assembly for a file
src/utils/FileReader.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/utils/FileReader.cpp.s
.PHONY : src/utils/FileReader.cpp.s

src/utils/IndieStudio.o: src/utils/IndieStudio.cpp.o

.PHONY : src/utils/IndieStudio.o

# target to build an object file
src/utils/IndieStudio.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/utils/IndieStudio.cpp.o
.PHONY : src/utils/IndieStudio.cpp.o

src/utils/IndieStudio.i: src/utils/IndieStudio.cpp.i

.PHONY : src/utils/IndieStudio.i

# target to preprocess a source file
src/utils/IndieStudio.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/utils/IndieStudio.cpp.i
.PHONY : src/utils/IndieStudio.cpp.i

src/utils/IndieStudio.s: src/utils/IndieStudio.cpp.s

.PHONY : src/utils/IndieStudio.s

# target to generate assembly for a file
src/utils/IndieStudio.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/utils/IndieStudio.cpp.s
.PHONY : src/utils/IndieStudio.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... edit_cache"
	@echo "... src/core/main.o"
	@echo "... src/core/main.i"
	@echo "... src/core/main.s"
	@echo "... src/entity/AEntity.o"
	@echo "... src/entity/AEntity.i"
	@echo "... src/entity/AEntity.s"
	@echo "... src/entity/bomb/Bomb.o"
	@echo "... src/entity/bomb/Bomb.i"
	@echo "... src/entity/bomb/Bomb.s"
	@echo "... src/entity/character/ACharacter.o"
	@echo "... src/entity/character/ACharacter.i"
	@echo "... src/entity/character/ACharacter.s"
	@echo "... src/entity/character/AI/AI.o"
	@echo "... src/entity/character/AI/AI.i"
	@echo "... src/entity/character/AI/AI.s"
	@echo "... src/entity/character/player/APlayerController.o"
	@echo "... src/entity/character/player/APlayerController.i"
	@echo "... src/entity/character/player/APlayerController.s"
	@echo "... src/entity/character/player/Control.o"
	@echo "... src/entity/character/player/Control.i"
	@echo "... src/entity/character/player/Control.s"
	@echo "... src/entity/character/player/Player.o"
	@echo "... src/entity/character/player/Player.i"
	@echo "... src/entity/character/player/Player.s"
	@echo "... src/entity/fire/Fire.o"
	@echo "... src/entity/fire/Fire.i"
	@echo "... src/entity/fire/Fire.s"
	@echo "... src/entity/power_up/APowerUp.o"
	@echo "... src/entity/power_up/APowerUp.i"
	@echo "... src/entity/power_up/APowerUp.s"
	@echo "... src/entity/power_up/PowerUp.o"
	@echo "... src/entity/power_up/PowerUp.i"
	@echo "... src/entity/power_up/PowerUp.s"
	@echo "... src/entity/wall/AWall.o"
	@echo "... src/entity/wall/AWall.i"
	@echo "... src/entity/wall/AWall.s"
	@echo "... src/entity/wall/Wall.o"
	@echo "... src/entity/wall/Wall.i"
	@echo "... src/entity/wall/Wall.s"
	@echo "... src/finder/AFinder.o"
	@echo "... src/finder/AFinder.i"
	@echo "... src/finder/AFinder.s"
	@echo "... src/finder/Finder.o"
	@echo "... src/finder/Finder.i"
	@echo "... src/finder/Finder.s"
	@echo "... src/map/Entities.o"
	@echo "... src/map/Entities.i"
	@echo "... src/map/Entities.s"
	@echo "... src/map/Logger.o"
	@echo "... src/map/Logger.i"
	@echo "... src/map/Logger.s"
	@echo "... src/map/MapGenerator.o"
	@echo "... src/map/MapGenerator.i"
	@echo "... src/map/MapGenerator.s"
	@echo "... src/scenes/AScene.o"
	@echo "... src/scenes/AScene.i"
	@echo "... src/scenes/AScene.s"
	@echo "... src/scenes/AScenePlayerControls.o"
	@echo "... src/scenes/AScenePlayerControls.i"
	@echo "... src/scenes/AScenePlayerControls.s"
	@echo "... src/scenes/ControlMenu.o"
	@echo "... src/scenes/ControlMenu.i"
	@echo "... src/scenes/ControlMenu.s"
	@echo "... src/scenes/EventListener.o"
	@echo "... src/scenes/EventListener.i"
	@echo "... src/scenes/EventListener.s"
	@echo "... src/scenes/Game.o"
	@echo "... src/scenes/Game.i"
	@echo "... src/scenes/Game.s"
	@echo "... src/scenes/GameOver.o"
	@echo "... src/scenes/GameOver.i"
	@echo "... src/scenes/GameOver.s"
	@echo "... src/scenes/MainMenu.o"
	@echo "... src/scenes/MainMenu.i"
	@echo "... src/scenes/MainMenu.s"
	@echo "... src/scenes/Menu.o"
	@echo "... src/scenes/Menu.i"
	@echo "... src/scenes/Menu.s"
	@echo "... src/scenes/MenuPlayer.o"
	@echo "... src/scenes/MenuPlayer.i"
	@echo "... src/scenes/MenuPlayer.s"
	@echo "... src/scenes/Options.o"
	@echo "... src/scenes/Options.i"
	@echo "... src/scenes/Options.s"
	@echo "... src/scenes/Pause.o"
	@echo "... src/scenes/Pause.i"
	@echo "... src/scenes/Pause.s"
	@echo "... src/scenes/Scenes.o"
	@echo "... src/scenes/Scenes.i"
	@echo "... src/scenes/Scenes.s"
	@echo "... src/scenes/WinMenu.o"
	@echo "... src/scenes/WinMenu.i"
	@echo "... src/scenes/WinMenu.s"
	@echo "... src/tools/Tools.o"
	@echo "... src/tools/Tools.i"
	@echo "... src/tools/Tools.s"
	@echo "... src/utils/FileReader.o"
	@echo "... src/utils/FileReader.i"
	@echo "... src/utils/FileReader.s"
	@echo "... src/utils/IndieStudio.o"
	@echo "... src/utils/IndieStudio.i"
	@echo "... src/utils/IndieStudio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

